# Data exploration and hypothesis testing

**The goal:** Data exploration and t-test

### Imports and data loading

In [1]:
import pandas as pd
from scipy import stats
import numpy as np

In [3]:
# Load dataset 
df = pd.read_csv('waze_dataset.csv')
df.head()

,ID,label,sessions,drives,total_sessions,n_days_after_onboarding,total_navigations_fav1,total_navigations_fav2,driven_km_drives,duration_minutes_drives,activity_days,driving_days,device
0,0,retained,283,226,296.748273,2276,208,0,2628.845068,1985.775061,28,19,Android
1,1,retained,133,107,326.896596,1225,19,64,13715.920550,3160.472914,13,11,iPhone
2,2,retained,114,95,135.522926,2651,0,0,3059.148818,1610.735904,14,8,Android
3,3,retained,49,40,67.589221,15,322,7,913.591123,587.196542,7,3,iPhone
4,4,retained,84,68,168.247020,1562,166,5,3950.202008,1219.555924,27,18,Android

###  Data exploration and encoding variables

In [7]:
# 1. Create `map_dictionary`
map_dictionary = {'iPhone' : 1, 'Android' : 2}

# 2. Create new `device_type` column
df['device_type'] = df['device']

# 3. Map the new column to the dictionary
df['device_type'] = df['device_type'].map(map_dictionary)
df.head()

,ID,label,sessions,drives,total_sessions,n_days_after_onboarding,total_navigations_fav1,total_navigations_fav2,driven_km_drives,duration_minutes_drives,activity_days,driving_days,device,device_type
0,0,retained,283,226,296.748273,2276,208,0,2628.845068,1985.775061,28,19,Android,2
1,1,retained,133,107,326.896596,1225,19,64,13715.920550,3160.472914,13,11,iPhone,1
2,2,retained,114,95,135.522926,2651,0,0,3059.148818,1610.735904,14,8,Android,2
3,3,retained,49,40,67.589221,15,322,7,913.591123,587.196542,7,3,iPhone,1
4,4,retained,84,68,168.247020,1562,166,5,3950.202008,1219.555924,27,18,Android,2

In [9]:
Iphone = df[df['device_type'] == 1]
Android = df[df['device_type'] == 2]
Iphone['drives'].mean(), Android['drives'].mean()

(67.85907775020678, 66.23183780739629)


### Task 3. Hypothesis testing

* **Null** -- There is no difference between who use android and who use iphone
* **Alternative** -- there is a difference between who use android and who use iphone

5% as the significance level

In [10]:
# Perform the t-test
stats.ttest_ind(Iphone['drives'], Android['drives'], equal_var = False)

Ttest_indResult(statistic=1.4635232068852353, pvalue=0.1433519726802059)

**Since pvalue is greater than significance level I fail to reject the null values, so there is no difference between who use the two devices**